
package grupo65universidad.Vistas;

import javax.swing.table.DefaultTableModel;


public class Inscripciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inscripciones
     */
    public Inscripciones() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLSeleccionAlumno = new javax.swing.JLabel();
        jCBSeleccionAlumno = new javax.swing.JComboBox<>();
        jLListadoMaterias = new javax.swing.JLabel();
        jRBMInscriptas = new javax.swing.JRadioButton();
        jRBMNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        jBInscribir = new javax.swing.JButton();
        jBAnularInscripcion = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 0));
        setClosable(true);
        setTitle("Formulario de Inscripcion");

        jLSeleccionAlumno.setText("Seleccione un alumno :");

        jLListadoMaterias.setText("Listado de Materias");

        jRBMInscriptas.setText("Materias Inscriptas");

        jRBMNoInscriptas.setText("Materias no Inscriptas");

        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaMaterias);

        jBInscribir.setText("Inscribir");

        jBAnularInscripcion.setText("Anular Inscripcion");

        jBSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLSeleccionAlumno)
                        .addGap(36, 36, 36)
                        .addComponent(jCBSeleccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jRBMInscriptas)
                        .addGap(143, 143, 143)
                        .addComponent(jRBMNoInscriptas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLListadoMaterias))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBInscribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAnularInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBSalir)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBSeleccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSeleccionAlumno))
                .addGap(27, 27, 27)
                .addComponent(jLListadoMaterias)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRBMNoInscriptas)
                    .addComponent(jRBMInscriptas))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jBAnularInscripcion)
                    .addComponent(jBSalir))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JButton jBAnularInscripcion;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCBSeleccionAlumno;
    private javax.swing.JLabel jLListadoMaterias;
    private javax.swing.JLabel jLSeleccionAlumno;
    private javax.swing.JRadioButton jRBMInscriptas;
    private javax.swing.JRadioButton jRBMNoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private DefaultTableModel modelo=new DefaultTableModel()
{public boolean isCellEditable(int fila,int columna){
return true;//o return false
// o if(columna==2){}
}
};

private void armarCabecera(){
modelo.addColumn("Id");
modelo.addColumn("Nombre");
modelo.addColumn("Año");
}

//lista de productos por rubro
//private void jcbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {                                             
//        borrarFilas();
//        String valor = String.valueOf(jcbCategoria.getSelectedItem());
//        String valor2 = null;
//
//        Categoria catseleccionada = (Categoria) jcbCategoria.getSelectedItem();
//
//        for (Producto producto : Menuprincipal.listaProductos) {
//
//            valor2 = String.valueOf(producto.getRubro());
//
//            if (valor.equals(valor2)) {
//
//                modelo.addRow(new Object[]{
//                    producto.getCodigo(),
//                    producto.getDescripcion(),
//                    producto.getPrecio(),
//                    producto.getStock()
//                });
//
//            }
//
//        }
//
//    }                                            

}